# Работа с пользовательским вводом. Сложение чисел. Часть 3

Всё работает отлично, если мы вписываем в `prompt` числа.
Но если ввести ввести символ вместо числа, то нас ждёт неожиданное
поведение. В результате функция сработает и не вызовет выброса
исключения, а в `alert`-е будет выведено `NaN`, что означает 
`not a number`.

Почему же не выбрасывается исключение? Потому, что `typeof NaN`
возвращает `'number'`. 

Откуда взялось `NaN`? В нашем случае, при попытке преобразовать
симольную строку в число, значение преобразовывается в `NaN`.

## Задача

Помимо проверки на то, что аргументы - числа, 
добавьте проверку на NaN.

*Со звёздочкой:*

Теперь, когда наша функция ругается на невалидные данные, нам будет
просто об этом узнать на этапе разработки, и код с ошибкой не попадёт в 
production.

Но теперь возникает вопрос, должны ли мы обрабатывать исключение,
чтобы сообщить об этом пользователю, или выполнять повторную проверку
данных до вызова функции?